=== PogiAbel/TR6FKPXML/TR6FKP_0924/TR6FKP_kurzusfelvetel.dtd
<!ELEMENT TR6FKP_kurzusfelvetel (hallgato, kurzusok)>
<!ATTLIST TR6FKP_kurzusfelvetel tanev CDATA #REQUIRED>
<!ATTLIST TR6FKP_kurzusfelvetel egyetem CDATA #REQUIRED>

<!ELEMENT hallgato (hnev, szulev, szak)>
<!ELEMENT hnev (#PCDATA)>
<!ELEMENT szulev (#PCDATA)>
<!ELEMENT szak (#PCDATA)>
<!ATTLIST szak evf CDATA #REQUIRED>

<!ELEMENT kurzusok (kurzus*)>
<!ELEMENT kurzus (kurzusnev, kredit, hely, idopont+, oktato?, oraado?)>
<!ATTLIST kurzus id ID #REQUIRED>
<!ATTLIST kurzus jovahagyas (igen | nem) "nem" >
<!ATTLIST kurzus nyelv (angol | magyar) "magyar">
<!ELEMENT kurzusnev (#PCDATA)>
<!ELEMENT kredit (#PCDATA)>
<!ELEMENT hely (#PCDATA)>
<!ELEMENT idopont (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>
<!ELEMENT oraado (#PCDATA)>

=== PogiAbel/TR6FKPXML/TR6FKP_0924/TR6FKP_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE TR6FKP_kurzusfelvetel SYSTEM "TR6FKP_kurzusfelvetel.dtd">

<TR6FKP_kurzusfelvetel tanev="2024/2025/I" egyetem="ME">
    <hallgato>
        <hnev>PA</hnev>
        <szulev>2001</szulev>
        <szak evf="3">Programtervező Informatikus</szak>
    </hallgato>
    <kurzusok>

        <kurzus id="GEIAL332-B" jovahagyas="igen" nyelv="magyar">
            <kurzusnev>Adatkezelés XML-ben</kurzusnev>
            <kredit>5</kredit>
            <hely>Inf/103</hely>
            <idopont>K:10-12</idopont>
            <oktato>Dr. Bednarik László</oktato>
            <oraado>Dr. Bednarik László</oraado>
        </kurzus>
        <kurzus id="GEIAK130-B" jovahagyas="igen" nyelv="magyar">
            <kurzusnev>Mesterséges intelligencia alapok</kurzusnev>
            <kredit>5</kredit>
            <hely>E32</hely>
            <idopont>SZ:16-18</idopont>
            <oktato>Fazekas Levente Áron</oktato>
            <oraado>Fazekas Levente Áron</oraado>
        </kurzus>
        <kurzus id="GEMAK253-B">
            <kurzusnev>Szakdolgozatkészítés I.</kurzusnev>
            <kredit>5</kredit>
            <hely></hely>
            <idopont></idopont>
            <oktato>Dr. Fegyverneki Sándor</oktato>
        </kurzus>
    </kurzusok>

</TR6FKP_kurzusfelvetel>
