<?xml version="1.0" encoding="UTF-8"?>

<!-- <!DOCTYPE PA_orarend SYSTEM "TR6FKP_orarend.dtd"> -->

<!DOCTYPE PA_orarend [
    <!ELEMENT PA_orarend (ora)*>
    <!ELEMENT ora (targy, idopont, helyszin, oktato, szak)>
    <!ATTLIST ora id CDATA #REQUIRED>
    <!ATTLIST ora tipus (eloadas | gyakorlat) "eloadas">
    <!ELEMENT targy (#PCDATA)>
    <!ELEMENT idopont (nap, tol, ig)>
    <!ELEMENT nap (#PCDATA)>
    <!ELEMENT tol (#PCDATA)>
    <!ELEMENT ig (#PCDATA)>
    <!ELEMENT helyszin (#PCDATA)>
    <!ELEMENT oktato (#PCDATA)>
    <!ELEMENT szak (#PCDATA)>
]>

<PA_orarend>
    <ora id="01" tipus="eloadas">
        <targy>Adatkezelés XML-ben</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>10</tol>
            <ig>12</ig>
        </idopont>
        <helyszin>Inf/103</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
    <ora id="02" tipus="gyakorlat">
        <targy>Adatkezelés XML-ben</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>10</tol>
            <ig>12</ig>
        </idopont>
        <helyszin>Inf/103</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
    <ora id="03" tipus="gyakorlat">
        <targy>Mesterséges intelligencia alapok</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>10</tol>
            <ig>12</ig>
        </idopont>
        <helyszin>E10</helyszin>
        <oktato>Fazekas Levente Áron</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
    <ora id="04" tipus="eloadas">
        <targy>Adatkezelés XML-ben</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>16</tol>
            <ig>18</ig>
        </idopont>
        <helyszin>E32</helyszin>
        <oktato>Kunné Dr. Tamás Judit</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
</PA_orarend>
