=== PogiAbel/TR6FKPXML/XMLTaskTR6FKP/DOMParseTR6FKP/XMLSchemaTR6FKP.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified">

    <!-- Sajat tipusok deklaralasa -->
    <xs:element name="TR6FKP_Iskolak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="iskola" type="iskolaTipus" maxOccurs="unbounded"/>
                <xs:element name="dolgozo" type="dolgozoTipus" maxOccurs="unbounded"/>
                <xs:element name="igazgato" type="igazgatoTipus" maxOccurs="unbounded"/>
                <xs:element name="tanar" type="tanarTipus" maxOccurs="unbounded"/>
                <xs:element name="oktat" type="oktatTipus" maxOccurs="unbounded"/>
                <xs:element name="tanulo" type="tanuloTipus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        
        <!-- Pk kulcsok deklaralasa -->
        <xs:key name="iskola_kulcs">
            <xs:selector xpath="iskola"/>
            <xs:field xpath="@iskola_id"/>
        </xs:key>
        
        <xs:key name="dolgozo_kulcs">
            <xs:selector xpath="dolgozo"/>
            <xs:field xpath="@dolgozo_id"/>
        </xs:key>
        
        <xs:key name="igazgato_kulcs">
            <xs:selector xpath="igazgato"/>
            <xs:field xpath="@igazgato_id"/>
        </xs:key>
        
        <xs:key name="tanar_kulcs">
            <xs:selector xpath="tanar"/>
            <xs:field xpath="@tanar_id"/>
        </xs:key>
        
        <xs:key name="tanulo_kulcs">
            <xs:selector xpath="tanulo"/>
            <xs:field xpath="@tanulo_id"/>
        </xs:key>
        
        <!-- Idegen kulcsok deklaralasa -->
        <xs:keyref refer="iskola_kulcs" name="dolgozo_idegen_kulcs" >
            <xs:selector xpath="dolgozo"/>
            <xs:field xpath="@iskola_fid"/>
        </xs:keyref>
        
        <xs:keyref refer="iskola_kulcs" name="igazgato_idegen_kulcs" >
            <xs:selector xpath="igazgato"/>
            <xs:field xpath="@iskola_fid"/>
        </xs:keyref>
        
        <xs:keyref refer="tanar_kulcs" name="tanar_oktat_idegen_kulcs" >
            <xs:selector xpath="oktat"/>
            <xs:field xpath="@tanar_fid"/>
        </xs:keyref>

        <xs:keyref refer="iskola_kulcs" name="iskola_oktat_idegen_kulcs" >
            <xs:selector xpath="oktat"/>
            <xs:field xpath="@iskola_fid"/>
        </xs:keyref>
        
        <xs:keyref refer="tanar_kulcs" name="tanar_tanulo_idegen_kulcs" >
            <xs:selector xpath="tanulo"/>
            <xs:field xpath="@tanar_fid"/>
        </xs:keyref>
        
        <xs:keyref refer="iskola_kulcs" name="iskola_tanulo_idegen_kulcs" >
            <xs:selector xpath="tanulo"/>
            <xs:field xpath="@iskola_fid"/>
        </xs:keyref>
        
        <!-- 1:1 kapcsolat megavolsitasa -->
        <xs:unique name="unique_igazgato">
            <xs:selector xpath="igazgato"/>
            <xs:field xpath="@iskola_fid"/>
        </xs:unique>

    </xs:element>
        
    <!-- Komplex tipusok deklaralasa -->
    <xs:complexType name="iskolaTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="cim" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="iskola_id" type="xs:string" use="required"/>
        <xs:attribute name="tanulok_szama">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:minInclusive value="0"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="dolgozoTipus">
        <xs:sequence>
            <xs:element name="nev" type="nevTipus"/>
            <xs:element name="fizetes" type="fizetesTipus"/>
            <xs:element name="beosztas" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="dolgozo_id" type="xs:string" use="required"/>
        <xs:attribute name="iskola_fid" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="nevTipus">
        <xs:sequence>
            <xs:element name="vezeteknev" type="xs:string"/>
            <xs:element name="keresztnev" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="fizetesTipus">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="igazgatoTipus">
        <xs:sequence>
            <xs:element name="nev" type="nevTipus"/>
            <xs:element name="fizetes" type="fizetesTipus"/>
            <xs:element name="telefonszam" type="telefonszamTipus" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="igazgato_id" type="xs:string" use="required"/>
        <xs:attribute name="iskola_fid" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:simpleType name="telefonszamTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="\+36/\d{2} \d{3}-\d{4}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="tanarTipus">
        <xs:sequence>
            <xs:element name="nev" type="nevTipus"/>
            <xs:element name="fizetes" type="xs:integer"/>
            <xs:element name="telefonszam" type="telefonszamTipus" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="diakok_szama">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="szak" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="tanar_id" type="xs:string" use="required"/>    </xs:complexType>

    <xs:complexType name="oktatTipus">
        <xs:sequence>
            <xs:element name="osztaly" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="iskola_fid" type="xs:string" use="required"/>
        <xs:attribute name="tanar_fid" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="tanuloTipus">
        <xs:sequence>
            <xs:element name="nev" type="nevTipus"/>
            <xs:element name="osztaly" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="tanulo_id" type="xs:string" use="required"/>
        <xs:attribute name="iskola_fid" type="xs:string" use="required"/>
        <xs:attribute name="tanar_fid" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== PogiAbel/TR6FKPXML/XMLTaskTR6FKP/DOMParseTR6FKP/XMLTR6FKP.xml
<?xml version="1.0" encoding="UTF-8"?>

<TR6FKP_Iskolak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="XMLSchemaTR6FKP.xsd">

    <!-- Iskolák -->

    <iskola iskola_id="i1" tanulok_szama="111">
        <nev>Minta Iskola 1</nev>
        <cim>Minta cím 1</cim>
    </iskola>

    <iskola iskola_id="i2" tanulok_szama="222">
        <nev>Minta Iskola 2</nev>
        <cim>Minta cím 2</cim>
    </iskola>

    <iskola iskola_id="i3" tanulok_szama="333">
        <nev>Minta Iskola 3</nev>
        <cim>Minta cím 3</cim>
    </iskola>

    <!-- Dolgozók -->

    <dolgozo dolgozo_id="d1" iskola_fid="i1">
        <nev>
            <vezeteknev>Minta</vezeteknev>
            <keresztnev>János</keresztnev>
        </nev>
        <fizetes>10000</fizetes>
        <beosztas>Mosogató</beosztas>
    </dolgozo>

    <dolgozo dolgozo_id="d2" iskola_fid="i2">
        <nev>
            <vezeteknev>Minta</vezeteknev>
            <keresztnev>Péter</keresztnev>
        </nev>
        <fizetes>12000</fizetes>
        <beosztas>Szakács</beosztas>
    </dolgozo>

    <dolgozo dolgozo_id="d3" iskola_fid="i3">
        <nev>
            <vezeteknev>Minta</vezeteknev>
            <keresztnev>Ákos</keresztnev>
        </nev>
        <fizetes>14000</fizetes>
        <beosztas>Gondnok</beosztas>
    </dolgozo>

    <!-- Igazgatók -->

    <igazgato igazgato_id="i1" iskola_fid="i1">
        <nev>
            <vezeteknev>Gazdag</vezeteknev>
            <keresztnev>István</keresztnev>
        </nev>
        <fizetes>180000</fizetes>
        <telefonszam>+36/70 123-1234</telefonszam>
        <telefonszam>+36/70 123-1244</telefonszam>
    </igazgato>

    <igazgato igazgato_id="i2" iskola_fid="i2">
        <nev>
            <vezeteknev>Gazdag</vezeteknev>
            <keresztnev>Kornél</keresztnev>
        </nev>
        <fizetes>200000</fizetes>
        <telefonszam>+36/70 111-1234</telefonszam>
        <telefonszam>+36/70 112-1234</telefonszam>
    </igazgato>

    <igazgato igazgato_id="i3" iskola_fid="i3">
        <nev>
            <vezeteknev>Gazdag</vezeteknev>
            <keresztnev>Sándor</keresztnev>
        </nev>
        <fizetes>280000</fizetes>
        <telefonszam>+36/70 003-1234</telefonszam>
        <telefonszam>+36/70 023-1234</telefonszam>
        <telefonszam>+36/70 000-1234</telefonszam>
    </igazgato>

    <!-- Tanárok -->

    <tanar tanar_id="t1">
        <nev>
            <vezeteknev>Szegény</vezeteknev>
            <keresztnev>Éva</keresztnev>
        </nev>
        <fizetes>50000</fizetes>
        <telefonszam>+36/20 001-0002</telefonszam>
        <diakok_szama>0</diakok_szama>
        <szak>Kémia</szak>
        <szak>Angol</szak>
    </tanar>

    <tanar tanar_id="t2">
        <nev>
            <vezeteknev>Szegény</vezeteknev>
            <keresztnev>Irén</keresztnev>
        </nev>
        <fizetes>45000</fizetes>
        <telefonszam>+36/20 111-0002</telefonszam>
        <diakok_szama>30</diakok_szama>
        <szak>Magyar</szak>
        <szak>Matek</szak>
    </tanar>

    <tanar tanar_id="t3">
        <nev>
            <vezeteknev>Szegény</vezeteknev>
            <keresztnev>Mária</keresztnev>
        </nev>
        <fizetes>30000</fizetes>
        <telefonszam>+36/20 001-1122</telefonszam>
        <diakok_szama>60</diakok_szama>
        <szak>Tesi</szak>
    </tanar>

    <!-- Tanárok - Iskola n:m kapcsolatok -->

    <oktat iskola_fid="i1" tanar_fid="t1"/>

    <oktat iskola_fid="i2" tanar_fid="t2">
        <osztaly>10c</osztaly>
    </oktat>

    <oktat iskola_fid="i1" tanar_fid="t3">
        <osztaly>11c</osztaly>
    </oktat>

    <oktat iskola_fid="i2" tanar_fid="t3">
        <osztaly>9a</osztaly>
        <osztaly>10a</osztaly>
    </oktat>

    <!-- Tanulók -->

    <tanulo tanulo_id="t1" iskola_fid="i1" tanar_fid="t3">
        <nev>
            <vezeteknev>Sima</vezeteknev>
            <keresztnev>Áron</keresztnev>
        </nev>
        <osztaly>10c</osztaly>
    </tanulo>

    <tanulo tanulo_id="t2" iskola_fid="i2" tanar_fid="t3">
        <nev>
            <vezeteknev>Sima</vezeteknev>
            <keresztnev>Anna</keresztnev>
        </nev>
        <osztaly>11c</osztaly>
    </tanulo>

    <tanulo tanulo_id="t3" iskola_fid="i3" tanar_fid="t2">
        <nev>
            <vezeteknev>Sima</vezeteknev>
            <keresztnev>Eszter</keresztnev>
        </nev>
        <osztaly>9a</osztaly>
    </tanulo>

</TR6FKP_Iskolak>
